Algoritmo "AnalisadorStrings"

Var
N: Caractere


Inicio
   Escreva ("Digite seu nome")
   Leia (N)
   EscrevaL ("Total de letras do seu nome: ", Compr (N))
   EscrevaL ("Seu nome em maiusculas e ", Maiusc (N))
   EscrevaL ("Seu nome em minusculas é ", Minusc (N))
   EscrevaL ("A primeira letra do seu nome é ", Copia (N, 1, 1))
   EscrevaL ("Seu nome tem a letra E na posição ", Pos("e", N))
   
Fimalgoritmo